version: "3.8"

services:
  postgres-server:
    image: diegmonti/test_db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres-server:postgres-server
