version: "3.8"

services:
  postgres-server:
    image: diegmonti/test_db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  postgres-client:
    image: postgres
    environment:
      - PGPASSWORD=mysecretpassword
    links:
      - postgres-server:postgres-server
    stdin_open: true
    tty: true
    command: "psql -h postgres-server -U postgres"
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres-server:postgres-server
